### ISSUE TITLE
Question about tools/load.py

### ISSUE THREAD

**Issue by BupyeongHealer** [StanfordVL/3DSceneGraph#12]
Hello, this is minseok kim. 
First of all, thank you for sharing awesome works!

Nowadays, I want to generate relation graph.
I have a question about loading function in tools/load.py.
Is the loading function replace with 1) framing step and 2) multi-view consistency?

Thanks!

**Comment by ir0** [comment]
Hi Minseok, 

If you want to use the annotated dataset we provide, you can use the `tools/load.py` file to load the annotations - however, as you probably noted, they do not include relationships but only attributes. You can use the functions in `source/3DSceneGraph/attributes/relationships.py` to query any of the relationships listed there or you can build your own functions if these are not covering the relationships you are looking to compute.

**Comment by BupyeongHealer** [comment]
Thank you for your quick response. I appreciate it.
