### ISSUE TITLE
Can't find 'individual room segmentation obj files' when running source/3DSceneGraph/main.py

### ISSUE THREAD

**Issue by youngmac1106** [StanfordVL/3DSceneGraph#13]
Thanks for your awesome work! As I running main.py, I find the absence of individual room segmentaion obj files, of which the path is generated in line 193 in function roomattrs() in main.py
`
    room_path = os.path.join(project_path, building.name, 'data', 'room')  # path to room segmentations
                                                                                                                    # (saved in individual .obj files)
`
I wonder if these file are generated by some of the previous steps or included in the gibson dataset? It seems that gibson dataset doesn't exist the individual room segmentation obj files or relevant information.

**Comment by ywh187** [comment]
it bothers me, too.

**Comment by cv4aec** [comment]
Thank for pointing this out. Actually there are no separate `.obj` files for room segmentation. This information is included in the `.npz` files of the dataset. To retrieve it you can use the code in the `tools` folder.

**Comment by ir0** [comment]
Thank for pointing this out. Actually there are no separate `.obj` files for room segmentation. This information is included in the `.npz` files of the dataset. To retrieve it you can use the code in the `tools` folder.
