### ISSUE TITLE
ground truth of panorama instance segmentation

### ISSUE THREAD

**Issue by ywh187** [StanfordVL/3DSceneGraph#14]
Hi, thanks for your awesome work that has taught me a lot. You tested panorama instance segmentation on the gibson dataset and got pretty good results in your paper.  How is the ground truth of instance segmentation made? Could you please share the ground truth? thanks a lot.

**Comment by ywh187** [comment]
![image](https://user-images.githubusercontent.com/67991061/157403464-6d0829b6-aff4-4329-bae0-34bd11cb14ce.png)
![p000001_object_class](https://user-images.githubusercontent.com/67991061/157404243-e9e3b3f5-683d-4fd0-820b-371fed4f766a.png)

hello, i have visualized the ground truth(verified_graph in tiny split), the result doesn't seem to be very good as the ground truth. Maybe I made a mistake. I would appreciate it if you could help me.

**Comment by ir0** [comment]
Despite manual verification the segmentation masks in ground truth (you are loading the correct file) might not be perfect. Keep in mind that the 2D image labels are a projection from the 3D mesh followed by a superpixel majority voting step.

**Comment by youngmac1106** [comment]
Hi
We visualize the verified result provided in the dataset, which as you describe is the **ground truth** in your experiment. Here is our visualization result.
![Visualize from the verified dataset](https://user-images.githubusercontent.com/91202359/157581644-3cba7c29-ac7b-4acb-b7a8-4468022c3fb0.png)

However, your paper post a different ground truth in supplement material. As shown in the figure bellow, you post a gt (bottom right) different from the above image we put, while the above image is much more similiar to your final result listed in the third colunm, d in the below image. 

![Screenshot from your supplement material](https://user-images.githubusercontent.com/91202359/157583203-87f2738b-f7aa-45a2-823b-d58bc17e09d0.png)

It seems that your experiment ground truth is differ from the real ground truth. I wonder did you put the wrong result  in the dataset? Or the picture we visualize from your verified dataset really is your experiment ground truth, which is also your experiment result?
