### ISSUE TITLE
Room Segmentation Files

### ISSUE THREAD

**Issue by aryanmangal769** [StanfordVL/3DSceneGraph#16]
To generate 3D scene Graph, In the third step it is required to give as input the Room Instance Segmentation files (.obj)
How can I download or generate them  ?

**Comment by ir0** [comment]
Hi, to generate the 3D Scene Graph you do not need any obj files of rooms. Any information on room instance segmentation is contained within the `.npz` files. Specifically under `data['building']['room_inst_segmentation']`, where `data` is the parameter that you load the `.npz` file of one building. This vector represents all the mesh faces of the building and each entry's value is the room unique id to which this face belongs.

**Comment by Wesley328** [comment]
I have the same problem，in the file named "run_main.sh",i want to know what the room_path should be.I don't seem to have a corresponding file
