### ISSUE TITLE
How can I get the detection

### ISSUE THREAD

**Issue by evenhax** [StanfordVL/3DSceneGraph#5]
I noticed these two lines in 3DSceneGraph/source/framing/pano_aggregation/run_panoaggreg.sh

```
model_path=/path/to/export/results      # system path to export results -- also contains the sampled frames and detection results
detection_folder=mask_rcnn     # name of folder that contains the detections

```
How can I get the detection results, Is this step contained in the project? Or I should get it by running mask_rcnn by myself ?

**Comment by evenhax** [comment]
@jgwak @yukezhu  Sorry for disturbing you by my junior question..

**Comment by xfyin1994** [comment]
@evenhax Hi! I am suffering the same question! And I still don't know how to get the `detection_folder`.

Could you please tell me how to get detection folder?
Is this generated from the `pano2rectilinear ` function in the `Framing` step?
Or should I run a Mask-RCNN code separately to generate the detection?

Thank you!

```
model_path=/path/to/export/results      # system path to export results -- also contains the sampled frames and detection results
override=0                              # binary value to override results (if 1 overrides)
detection_folder=mask_rcnn              # name of folder that contains the detections
panoaggreg_folder=pano_aggreg           # name of folder to export panorama aggregation results
```

**Comment by ir0** [comment]
As you both noted, you should run the instance segmentation algorithm of your preference separately. It is not included in this code repository. For example, we ran Mask-RCNN and BlitzNet. The only point to pay attention at is the structure of the expected input to the panorama aggregation (framing) step of the pipeline.
