### ISSUE TITLE
How can I get the relationship of 3D scene graph?I find it is not include in the dataset

### ISSUE THREAD

**Issue by xfyin1994** [StanfordVL/3DSceneGraph#7]
Hi @ir0 , I am interested in the **relationships** in this 3D SceneGraph Dataset. But I find this dataset only provides object attributes, and don't have the relationships such as Spatial Order or Occlusion Relationship. And in the **supplementary material** of this paper, I found there are no words to explain what method is used to compute the relationships. Did I miss something important about the relationship, whether in the dataset or in the paper?

In this issue, I wonder is that means I must run another code based on this 3DSceneGraph dataset to generate the relationships by myself? Just like you said, compute the relationships by the node annotations. And have you already released some relevant code? If so, I would be appreciated！

Thank you!

> The graph's nodes are provided with the annotations, which you can populate using the provided code. Since the graph is dense and there is a plethora of combinations to create between elements, we didn't provide relationship annotations. It should be relatively straightforward to compute queried relationships given the node annotations (e.g., relative volume between two objects or if two objects belong to the same space), but we are planning on releasing some code for that in the next weeks. Let me know if you have more questions.

_Originally posted by @ir0 in https://github.com/StanfordVL/3DSceneGraph/issues/3#issuecomment-564783087_

**Comment by ir0** [comment]
Hi @xfyin1994,

The code for getting attributes and relationships is in 3DSceneGraph/source/3DSceneGraph/main.py ([line](https://github.com/StanfordVL/3DSceneGraph/blob/ee1f63545a56f86de5f0957a611798f17c142137/source/3DSceneGraph/main.py#L380)).
