### ISSUE TITLE
Problem about get_globalindx_detections(det, global_indx, ratio) in pano_aggreg.py

### ISSUE THREAD

**Issue by YvonneZhao0305** [StanfordVL/3DSceneGraph#8]
In mask R-CNN, I got segmentations(without background label) above some rectilinear frames.
But In a specific rectilinear frame, I have no detections, resulting in a ZeroDivisionError.
Is this problem caused by no background label in the detection classes?
Please help me to solve it. @ir0 
`ZeroDivisionError

float division by zero
  File "/home/XXX/Projects/3DSceneGraph/source/framing/pano_aggregation/pano_aggreg.py", line 210, in get_globalindx_detections
    semt_scr[temp_ind] = ratio * 1.0/num_detect
  File "/home/XXX/Projects/3DSceneGraph/source/framing/pano_aggregation/pano_aggreg.py", line 753, in get_aggregated_frame_labels
    semt_lab, semt_scr = get_globalindx_detections(detections, global_indx, ratio)
  File "/home/XXX/Projects/3DSceneGraph/source/framing/pano_aggregation/pano_aggreg.py", line 840, in label_aggregation
    equ_img, rect2eq["frames"][frm_num], frm_num, ratio, interpol)
  File "/home/XXX/Projects/3DSceneGraph/source/framing/pano_aggregation/pano_aggreg.py", line 958, in <module>
    colors, class2col, ind2cat, cat2ind, thresh, ratio, interpol, VIS)`

**Comment by ir0** [comment]
Hi Yvonne,

You diagnosed the problem yourself - zero detections is the issue here. You cannot have a zero in the denominator variable num_detect, which is the total number of detections in the image (line 210, in get_globalindx_detections: semt_scr[temp_ind] = ratio * 1.0/num_detect). Add a check to make sure you don't go forward with processing a rectilinear frame if it has zero detections.

**Comment by YvonneZhao0305** [comment]
After I added a check to make sure 'num_detect > 0 ', I got some  strange  images as following.
![point_p000001_view_equirectangular_domain_rgb_vase](https://user-images.githubusercontent.com/45263155/93746785-484b3080-fc28-11ea-9f45-218b446eccf0.png)
![point_p000001_view_equirectangular_domain_rgb_kite](https://user-images.githubusercontent.com/45263155/93746803-4d0fe480-fc28-11ea-9353-21340c3a7a9b.png)
