### ISSUE TITLE
What is the object class "0"

### ISSUE THREAD

**Issue by Ainaz99** [StanfordVL/3DSceneGraph#9]
Hi, I have a question about the instances labeled with object class "0" in the dataset. I produced some panorama images and only labeled the instances from class "0". So I don't understand why all these instances are labeled with class "0", and what category they actually belong to. The panorama images are as follows.
Thank you.
![1](https://user-images.githubusercontent.com/69212889/95499409-17058b00-09b2-11eb-879e-aef54753d451.png)
![2](https://user-images.githubusercontent.com/69212889/95499831-bb87cd00-09b2-11eb-85d7-fa26d359a9a0.png)
![5](https://user-images.githubusercontent.com/69212889/95500278-757f3900-09b3-11eb-9911-2edf507898f7.png)
![3](https://user-images.githubusercontent.com/69212889/95500378-96478e80-09b3-11eb-80db-33646c3d8527.png)

**Comment by ir0** [comment]
Hi Ainaz,

I suppose that these panoramas were created from the load.py function. Please note that these examples show the instance segmentation and not the object class (appears that these are the visualizations p000***_class_inst.png and not p000***_class_segm.png). If you want to visualize the classes, please use the other panorama file. Also, note that line 419 in load.py returns a panorama with the object class per pixel and line 420 one with the object instance.
